language: ruby
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - rbx-2.2.7
before_install:
  - wget http://downloads.sourceforge.net/project/cmusphinx/sphinxbase/0.8/sphinxbase-0.8.tar.gz
  - tar -zxf sphinxbase-0.8.tar.gz
  - cd sphinxbase-0.8
  - ./configure
  - make
  - sudo make install
  - wget http://downloads.sourceforge.net/project/cmusphinx/pocketsphinx/0.8/pocketsphinx-0.8.tar.gz
  - tar -zxf pocketsphinx-0.8.tar.gz
  - cd pocketsphinx-0.8
  - ./configure
  - make
  - sudo make install
